21 main view branch section
BC-MAY-21-ROR/kata-07-reloj-checador-k7-f22-t1 pull request #25
Opened 2022-03-19 04:32 UTC by femm34

# Description
What did you implemented
 - added a new method to search branches by name or address
 - added new styles to branches main view
Why did you implemented this:
 -  add this method to make it faster to search for any branch

  ## Screenshots
![image](https://user-images.githubusercontent.com/78227397/159106725-2ca6d466-4c62-4861-917b-e1999a6f1b2d.png)
![image](https://user-images.githubusercontent.com/78227397/159106755-8c3bf823-237f-4d03-bb5c-493c11ba649f.png)
![image](https://user-images.githubusercontent.com/78227397/159106853-9cc7a497-8e73-4cc1-9cd9-33266b0abdbf.png)

2022-03-21 22:00 UTC, YilKanda requested changes

2022-03-21 22:00 UTC, YilKanda commented on app/javascript/controllers/branches_controller.js
> +    console.log("Hello, Stimulus!", this.element);
It is not recommended to leave debugging code like console.log()

2022-03-21 22:00 UTC, YilKanda commented on app/javascript/controllers/branches_controller.js
> +  // static targets = ["button_new_branch"]
Code that you do not occupy delete it.

2022-03-22 20:11 UTC, femm34 commented on app/javascript/controllers/branches_controller.js
> +    console.log("Hello, Stimulus!", this.element);
@YilKanda thanks, im gonna delete it

2022-03-22 20:12 UTC, femm34 commented on app/javascript/controllers/branches_controller.js
> +  // static targets = ["button_new_branch"]
@YilKanda thansk , im gonna do it

2022-03-22 22:23 UTC, YilKanda approved these changes

2022-03-22 23:16 UTC, EliasUR approved these changes
LGTM ;)

2022-03-22 23:49 UTC, AlejandroCuriel approved these changes
LGTM :rocket: :eagle:

2022-03-23 00:26 UTC, merged